import { createElement } from 'lwc';
import Day11Assignment2CreateAccountContactOpportunity from 'c/day11Assignment2CreateAccountContactOpportunity';

describe('c-day11-assignment2-create-account-contact-opportunity', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-day11-assignment2-create-account-contact-opportunity', {
            is: Day11Assignment2CreateAccountContactOpportunity
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});