import { createElement } from 'lwc';
import Day14Assignment3ShowDeatailsOfEachAccount from 'c/day14Assignment3ShowDeatailsOfEachAccount';

describe('c-day14-assignment3-show-deatails-of-each-account', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-day14-assignment3-show-deatails-of-each-account', {
            is: Day14Assignment3ShowDeatailsOfEachAccount
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});