import { createElement } from 'lwc';
import LdsDay10UpdaterecordAssignment3 from 'c/ldsDay10UpdaterecordAssignment3';

describe('c-lds-day10-updaterecord-assignment3', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lds-day10-updaterecord-assignment3', {
            is: LdsDay10UpdaterecordAssignment3
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});